### PR TITLE
Milestone 1

### PR DESCRIPTION
**Pull request by WCanirinka**
After creating the ERD, we would like to ask for a review.

### CODE REVIEW

**Comment by samgaco** [comment]
Hi @WCanirinka and @300ms :high_brightness: 

Everything looks ok, but the _**like**_ model should just be modeled in one table... and then you could change the name through associations if that is your wish (to have separate comment  likes and post likes) , with something like:

`has_many :comment_likes, :class_name => "Like"
`


Try to modify that and submit back for another review. Regards!
------------------------
* ###### STATUS OF THE PROJECT: REQUESTED CHANGES :stop_sign:

**Comment by WCanirinka** [comment]
Updated the ERD Like model and would like a new request. The stickler error is because I enabled the stickler on the project and the milestone does not have a .stickler.yml file

**Review by Redvanisation — CHANGES_REQUESTED** [review]
# Changes required  ♻️ 

### Hello team  🌟

**Very nice work on this project, however, the following issues need to be fixed before moving on ⬇️** 

- Everything looks fine for me, you just have to fix the linter's errors.

### _After making the required changes please submit a new code review request_

### Good luck! 🍀

**Review by ebukaume — APPROVED** [review]
Hi @WCanirinka and @300ms :wave: 

Even though you guys do not have linter on this repo, I am going to approve it because there really is nothing to linter yet!. But next time, please setup your app even if you are not writing codes yet to avoid issues with your git history. **You can go ahead with the next milestone!**

Happy Coding :v: 
**Ebuka Umeokonkwo**
 [Github](https://github.com/ebukaume) | [Linkedin](https://www.linkedin.com/in/ebukaume) | [Slack](https://app.slack.com/team/UFDKXE68L) | [Twitter](https://twitter.com/ebukaume)

**Pull request merged**
